/* Purifreze · blog content — sample dataset
   "Agua Viva en Yucatán" uses the real copy from the current site. */
window.PF_AUTHORS = {
  ren: { name: 'Renata Cámara', initials: 'RC' },
  jor: { name: 'Jorge Méndez',  initials: 'JM' },
  pao: { name: 'Paola Ruiz',    initials: 'PR' },
};

// flat placeholder cover (design-system rule: slate fill + brand-tinted icon)
function cv(color, icon){ return { color, icon }; }

window.PF_ARTICLES = [
  {
    id:'agua-viva-yucatan',
    title:'Agua Viva en Yucatán',
    excerpt:'5 razones para dejar de consumir agua muerta',
    slug:'/blog/agua-viva-en-yucatan',
    category:'Agua',
    status:'pub', date:'20/03/2026', dateNice:'20 mar 2026', views:1204, readMin:4,
    author:'ren',
    cover:cv('#3a2e6e','flask'),
    metaTitle:'Agua Viva en Yucatán — 5 razones para dejar el agua muerta',
    metaDesc:'Descubre por qué el agua viva mejora tu bienestar y cómo la desinfección cuántica de Purifreze elimina microorganismos en Yucatán.',
    keyword:'agua viva yucatán',
    blocks:[
      { type:'p', html:'La <b>desinfección cuántica</b> se refiere a tecnologías innovadoras que utilizan principios de la mecánica cuántica para eliminar microorganismos del agua sin alterar su estructura natural.' },
      { type:'h2', html:'Beneficios de consumir agua viva' },
      { type:'list', items:['Mantiene los minerales esenciales que tu cuerpo necesita','Mejora la hidratación celular y la digestión','Sin cloro residual ni sabor metálico'] },
      { type:'p', html:'A diferencia del agua embotellada que lleva meses almacenada, el agua viva conserva su vitalidad porque se purifica en el punto de consumo.' },
      { type:'quote', html:'El agua no solo debe estar limpia: debe estar viva.' },
      { type:'callout', html:'¿Tienes dudas sobre la calidad del agua en tu zona? Agenda una prueba gratuita con un técnico Purifreze.' },
      { type:'p', html:'Conoce más sobre nuestro proceso de <a href="#">desinfección cuántica</a> y cómo lo aplicamos en cada instalación.' },
    ],
  },
  {
    id:'vida-camara-frigorifica',
    title:'Cómo prolongar la vida de tu cámara frigorífica',
    excerpt:'Guía práctica para el mantenimiento de equipos de refrigeración industrial y ahorro energético.',
    slug:'/blog/vida-camara-frigorifica',
    category:'Equipo',
    status:'pub', date:'18/03/2026', dateNice:'18 mar 2026', views:982, readMin:6,
    author:'jor',
    cover:cv('#0b3a5e','snow'),
    metaTitle:'Cómo prolongar la vida de tu cámara frigorífica',
    metaDesc:'Guía práctica de Purifreze para el mantenimiento de equipos de refrigeración industrial y ahorro energético.',
    keyword:'mantenimiento refrigeración',
  },
  {
    id:'senales-purificador-servicio',
    title:'5 señales de que tu purificador necesita servicio',
    excerpt:'Sabor raro, presión baja o filtros saturados: aprende a leer las alertas antes de que el agua lo resienta.',
    slug:'/blog/senales-purificador-servicio',
    category:'Equipo',
    status:'pub', date:'14/03/2026', dateNice:'14 mar 2026', views:1530, readMin:5,
    author:'pao',
    cover:cv('#155e4b','gauge'),
    metaTitle:'5 señales de que tu purificador de agua necesita servicio',
    metaDesc:'Reconoce a tiempo cuándo tu purificador Purifreze necesita mantenimiento y evita consumir agua de baja calidad.',
    keyword:'servicio purificador agua',
  },
  {
    id:'lecturas-temperatura',
    title:'Guía rápida: lecturas de temperatura sin errores',
    excerpt:'El paso a paso que siguen nuestros técnicos para registrar lecturas confiables en campo.',
    slug:'/blog/lecturas-temperatura',
    category:'Mantenimiento',
    status:'draft', date:'12/03/2026', dateNice:'12 mar 2026', views:0, readMin:3,
    author:'jor',
    cover:null,
    metaTitle:'', metaDesc:'', keyword:'lecturas de temperatura',
  },
  {
    id:'refrigerante-r404a',
    title:'Refrigerante R-404A: qué saber antes de recargar',
    excerpt:'Presiones de trabajo, compatibilidad y los errores más caros al manipular R-404A.',
    slug:'/blog/refrigerante-r404a',
    category:'Equipo',
    status:'pub', date:'09/03/2026', dateNice:'09 mar 2026', views:744, readMin:7,
    author:'jor',
    cover:cv('#1e293b','flask'),
    metaTitle:'Refrigerante R-404A: guía antes de recargar',
    metaDesc:'Todo lo que un técnico debe revisar antes de recargar refrigerante R-404A en equipos de refrigeración industrial.',
    keyword:'refrigerante r-404a',
  },
  {
    id:'agua-dura-suave',
    title:'Agua dura vs. agua suave en tu hogar',
    excerpt:'Manchas blancas, jabón que no hace espuma y tuberías tapadas: la dureza del agua explica más de lo que crees.',
    slug:'/blog/agua-dura-suave',
    category:'Agua',
    status:'pub', date:'05/03/2026', dateNice:'05 mar 2026', views:2110, readMin:5,
    author:'pao',
    cover:null,
    metaTitle:'Agua dura vs. agua suave: cuál tienes en casa',
    metaDesc:'Aprende a identificar si tienes agua dura o suave y cómo afecta tu salud, tu piel y tus electrodomésticos.',
    keyword:'agua dura agua suave',
  },
  {
    id:'mantenimiento-preventivo-energia',
    title:'Mantenimiento preventivo que ahorra energía',
    excerpt:'Un equipo bien mantenido consume hasta 20% menos. Te decimos por dónde empezar.',
    slug:'/blog/mantenimiento-preventivo-energia',
    category:'Mantenimiento',
    status:'sched', date:'25/03/2026', dateNice:'25 mar 2026', views:0, readMin:6,
    author:'jor',
    cover:cv('#0b3a5e','snow'),
    metaTitle:'Mantenimiento preventivo que ahorra energía',
    metaDesc:'Cómo un plan de mantenimiento preventivo reduce el consumo eléctrico de tus equipos de refrigeración.',
    keyword:'mantenimiento preventivo energía',
  },
  {
    id:'cambiar-filtros',
    title:'¿Cada cuánto cambiar los filtros?',
    excerpt:'No hay una sola respuesta. Depende del uso, la fuente y la dureza del agua. Aquí la tabla que usamos.',
    slug:'/blog/cambiar-filtros',
    category:'Agua',
    status:'draft', date:'02/03/2026', dateNice:'02 mar 2026', views:0, readMin:4,
    author:'pao',
    cover:null,
    metaTitle:'', metaDesc:'', keyword:'cambiar filtros agua',
  },
  {
    id:'costo-fuga-refrigerante',
    title:'El costo real de una fuga de refrigerante',
    excerpt:'Más allá del gas perdido: energía, multas ambientales y daño al compresor.',
    slug:'/blog/costo-fuga-refrigerante',
    category:'Equipo',
    status:'pub', date:'26/02/2026', dateNice:'26 feb 2026', views:613, readMin:6,
    author:'jor',
    cover:cv('#3a2e6e','gauge'),
    metaTitle:'El costo real de una fuga de refrigerante',
    metaDesc:'Calcula el impacto económico y ambiental de una fuga de refrigerante y cómo prevenirla con Purifreze.',
    keyword:'fuga de refrigerante',
  },
  {
    id:'hidratacion-bienestar',
    title:'Hidratación y bienestar: mitos comunes',
    excerpt:'¿De verdad necesitas 8 vasos al día? Separamos el mito del dato.',
    slug:'/blog/hidratacion-bienestar',
    category:'Bienestar',
    status:'pub', date:'20/02/2026', dateNice:'20 feb 2026', views:1788, readMin:4,
    author:'pao',
    cover:cv('#155e4b','flask'),
    metaTitle:'Hidratación y bienestar: mitos comunes resueltos',
    metaDesc:'Desmentimos los mitos más comunes sobre la hidratación y el consumo de agua para tu bienestar diario.',
    keyword:'hidratación bienestar',
  },
  {
    id:'checklist-inspeccion-frio',
    title:'Checklist de inspección para cámaras de frío',
    excerpt:'Los 12 puntos que no pueden faltar en una visita de servicio.',
    slug:'/blog/checklist-inspeccion-frio',
    category:'Mantenimiento',
    status:'draft', date:'15/02/2026', dateNice:'15 feb 2026', views:0, readMin:3,
    author:'jor',
    cover:null,
    metaTitle:'', metaDesc:'', keyword:'inspección cámara de frío',
  },
  {
    id:'agua-muerta-salud',
    title:'Por qué el agua "muerta" afecta tu salud',
    excerpt:'Almacenada, sin oxígeno y con cloro residual: qué le pasa al agua que llevas semanas guardando.',
    slug:'/blog/agua-muerta-salud',
    category:'Bienestar',
    status:'sched', date:'28/03/2026', dateNice:'28 mar 2026', views:0, readMin:5,
    author:'ren',
    cover:cv('#1e293b','flask'),
    metaTitle:'Por qué el agua muerta afecta tu salud',
    metaDesc:'Qué le ocurre al agua almacenada por semanas y por qué el agua viva es mejor para tu salud.',
    keyword:'agua muerta salud',
  },
];

// default blocks for articles that don't ship explicit content
window.PF_DEFAULT_BLOCKS = function(a){
  return [
    { type:'p', html:'En Purifreze llevamos años cuidando el agua y los equipos de quienes confían en nosotros. '+(a.excerpt||'') },
    { type:'h2', html:'Lo esencial' },
    { type:'p', html:'Este es un borrador editable. Coloca el cursor en cualquier bloque y escribe; pulsa <b>“/”</b> para insertar un título, una lista, una imagen o una cita.' },
    { type:'list', items:['Primer punto clave','Segundo punto clave','Tercer punto clave'] },
    { type:'p', html:'Cierra con una invitación clara a la acción para tus lectores.' },
  ];
};
